# Generated by Django 6.0.4 on 2026-07-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação')),
                ('name', models.CharField(help_text='Nome do ambiente', max_length=255)),
                ('is_occupied', models.BooleanField(default=False, help_text='Status de ocupação atual')),
                ('target_consumption', models.FloatField(blank=True, help_text='Meta de consumo em kWh', null=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação')),
                ('name', models.CharField(help_text='Nome descritivo do Protótipo (Ex: NodeMCU_Lab01)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descrição ou anotações extras', null=True)),
                ('environment', models.ForeignKey(blank=True, help_text='Ambiente onde o protótipo está instalado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prototypes', to='sensors.environment')),
            ],
            options={
                'verbose_name': 'Protótipo',
                'verbose_name_plural': 'Protótipos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação')),
                ('temperature', models.FloatField(blank=True, help_text='Temperatura em °C', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Distância em cm', null=True)),
                ('current', models.FloatField(blank=True, help_text='Corrente elétrica em Amperes', null=True)),
                ('prototype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.prototype')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'ordering': ['-created_at'],
            },
        ),
    ]
