# Generated by Django 6.0.4 on 2026-05-26 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação')),
                ('name', models.CharField(help_text='Nome descritivo do sensor (Ex: Water Tank Sensor)', max_length=255)),
                ('type', models.CharField(help_text='Tipo do sensor (Ex: HC-SR04)', max_length=100)),
                ('unit', models.CharField(help_text='Unidade de medida (Ex: cm, °C, %)', max_length=50)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação')),
                ('value', models.FloatField(help_text='Valor lido pelo sensor', validators=[django.core.validators.MinValueValidator(0.0, message='O valor não pode ser negativo'), django.core.validators.MaxValueValidator(400.0, message='O valor não pode ser maior que 400 (para sensores de 400cm)')])),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'ordering': ['-created_at'],
            },
        ),
    ]
