# Generated by Django 6.0.4 on 2026-07-30 00:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última modificação')),
                ('name', models.CharField(help_text='Nome do ambiente', max_length=255)),
                ('is_occupied', models.BooleanField(default=False, help_text='Status de ocupação atual')),
                ('target_consumption', models.FloatField(blank=True, help_text='Meta de consumo em kWh', null=True)),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='reading',
            name='value',
            field=models.FloatField(help_text='Valor lido pelo sensor (distância, temperatura, estado PIR, etc)', validators=[django.core.validators.MinValueValidator(0.0, message='O valor não pode ser negativo')]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(help_text='Nome descritivo do sensor', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(help_text='Tipo do sensor (Ex: HC-SR04, PIR, DS18B20)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, help_text='Unidade de medida (Ex: cm, °C, bool, kWh)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='Ambiente onde o sensor está instalado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sensors.environment'),
        ),
    ]
