# Generated by Django 6.0.4 on 2026-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='presence',
            field=models.BooleanField(blank=True, help_text='Detectou Presença? (PIR)', null=True),
        ),
    ]
